### PR TITLE
fix: uploading same single image now gives same swarm reference hash

### LINKED ISSUE #101: Uploading the same file does not give the same hash
Despite #96. Requires more investigation.

### PR DESCRIPTION
**Pull request by vojtechsimetka**
resolves #101

### CODE REVIEW

**Comment by bee-worker** [comment]
## 🐝 PR preview in Swarm

**Preview URL:** https://bafybwicgmuvfhtqyhjtxzq7ycds3ta4rzh3lctbj3ai3zj6ybrrwko7wqa.bzz.link
**Swarm Hash:** `46652a53ce183a677cc3f810e5b98391c9f6b14c29d811bca7d80c63653bf680`
**Commit Hash:** 23c7511c0993669ae26b4dcc568ac499d8d2bf3a
**Commit Message:** fix: uploading same single image now gives same swarm reference hash

File: src/utils/image.ts [hunk 1]
```diff
@@ -0,0 +1,89 @@
...
+      'image/gif',
+      'image/vnd.microsoft.icon',
+      'image/jpeg',
+      'image/png',
+      'image/svg+xml',
+      'image/tiff',
+      'image/webp',
+    ]
+
+    if (!file.size || !file.type || !allowedTypes.includes(file.type)) reject('File not supported!')
```
Comment (Cafe137) [inline src/utils/image.ts:51]: Is this missing a `return`? I think `reject` on its own does not stop execution

Comment (vojtechsimetka) [reply src/utils/image.ts:51]: You are very right, this needs to have `return`

File: src/components/AssetPreview.tsx [hunk 2]
```diff
@@ -32,11 +33,9 @@ export function AssetPreview({ previewUri, metadata }: Props): ReactElement {
...
       <Box bgcolor="background.paper">
         <Grid container direction="row">
-          {previewUri ? (
-            <FitImage maxWidth="250px" maxHeight="175px" alt="Upload Preview" src={previewUri} />
-          ) : (
-            <AssetIcon icon={previewComponent} />
-          )}
+          <div style={{ width: PREVIEW_DIMENSIONS.maxWidth, height: PREVIEW_DIMENSIONS.maxHeight }}>
+            {previewUri ? <FitImage alt="Upload Preview" src={previewUri} /> : <AssetIcon icon={previewComponent} />}
+          </div>
```
Comment (Cafe137) [inline src/components/AssetPreview.tsx:38]: Should this wrapper `div` be part of the `FitImage` component?

As I understand, the functionality is the same just with a better approach (parent + scale-down object-fit), but it is not enclosed in a single component, and the `FitImage` is no longer true to its name as well in the current state 🙂

**Review by Cafe137 — CHANGES_REQUESTED** [review]
Nicely done, just had a few comments 🙂

File: src/components/AssetPreview.tsx (hunk 2 above)
Comment (Cafe137) [reply src/components/AssetPreview.tsx:38]: Ah I see it is more tricky because we also display the AssetIcon sometime.

Comment (vojtechsimetka) [reply src/components/AssetPreview.tsx:38]: So I actually decided it is best to always have this preview to be always the same size and only scale down the image inside the preview if needed (and for smaller images to not stretch them). This IMHO makes more sense because the layout always stays the same. But You are right that I should review how `AssetIcon` component works and maybe only need to size correctly the `FitImage`.

Comment (vojtechsimetka) [reply src/components/AssetPreview.tsx:38]: I edited it to now always have the same width and height (if there is an image preview or just icon).

**Review by Cafe137 — APPROVED** [review]
